// ============================================================================
// Nexus AI Engine - Protocole gRPC
// ============================================================================
//
// Ce fichier définit les services gRPC pour l'API Nexus.
// À compiler avec: protoc --go_out=. --go-grpc_out=. nexus.proto
//
// ============================================================================

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: nexus.proto

package nexus

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NexusService_Query_FullMethodName           = "/nexus.NexusService/Query"
	NexusService_QueryStream_FullMethodName     = "/nexus.NexusService/QueryStream"
	NexusService_ListSkills_FullMethodName      = "/nexus.NexusService/ListSkills"
	NexusService_GetSkillDetails_FullMethodName = "/nexus.NexusService/GetSkillDetails"
	NexusService_ListMCP_FullMethodName         = "/nexus.NexusService/ListMCP"
	NexusService_ConnectMCP_FullMethodName      = "/nexus.NexusService/ConnectMCP"
	NexusService_DisconnectMCP_FullMethodName   = "/nexus.NexusService/DisconnectMCP"
	NexusService_GetModels_FullMethodName       = "/nexus.NexusService/GetModels"
	NexusService_HealthCheck_FullMethodName     = "/nexus.NexusService/HealthCheck"
)

// NexusServiceClient is the client API for NexusService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NexusService est le service principal pour les interactions avec le moteur IA
type NexusServiceClient interface {
	// Exécute une requête simple (non-streaming)
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	// Exécute une requête en mode streaming (pour les réponses longues)
	QueryStream(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryResponse], error)
	// Liste tous les skills disponibles
	ListSkills(ctx context.Context, in *ListSkillsRequest, opts ...grpc.CallOption) (*ListSkillsResponse, error)
	// Retourne les détails d'un skill spécifique
	GetSkillDetails(ctx context.Context, in *GetSkillDetailsRequest, opts ...grpc.CallOption) (*GetSkillDetailsResponse, error)
	// Liste les serveurs MCP connectés
	ListMCP(ctx context.Context, in *ListMCPRequest, opts ...grpc.CallOption) (*ListMCPResponse, error)
	// Connecte à un serveur MCP
	ConnectMCP(ctx context.Context, in *ConnectMCPRequest, opts ...grpc.CallOption) (*ConnectMCPResponse, error)
	// Déconnecte un serveur MCP
	DisconnectMCP(ctx context.Context, in *DisconnectMCPRequest, opts ...grpc.CallOption) (*DisconnectMCPResponse, error)
	// Liste les modèles disponibles
	GetModels(ctx context.Context, in *GetModelsRequest, opts ...grpc.CallOption) (*GetModelsResponse, error)
	// Health check pour le monitoring
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type nexusServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNexusServiceClient(cc grpc.ClientConnInterface) NexusServiceClient {
	return &nexusServiceClient{cc}
}

func (c *nexusServiceClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, NexusService_Query_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nexusServiceClient) QueryStream(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NexusService_ServiceDesc.Streams[0], NexusService_QueryStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[QueryRequest, QueryResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NexusService_QueryStreamClient = grpc.ServerStreamingClient[QueryResponse]

func (c *nexusServiceClient) ListSkills(ctx context.Context, in *ListSkillsRequest, opts ...grpc.CallOption) (*ListSkillsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSkillsResponse)
	err := c.cc.Invoke(ctx, NexusService_ListSkills_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nexusServiceClient) GetSkillDetails(ctx context.Context, in *GetSkillDetailsRequest, opts ...grpc.CallOption) (*GetSkillDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSkillDetailsResponse)
	err := c.cc.Invoke(ctx, NexusService_GetSkillDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nexusServiceClient) ListMCP(ctx context.Context, in *ListMCPRequest, opts ...grpc.CallOption) (*ListMCPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMCPResponse)
	err := c.cc.Invoke(ctx, NexusService_ListMCP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nexusServiceClient) ConnectMCP(ctx context.Context, in *ConnectMCPRequest, opts ...grpc.CallOption) (*ConnectMCPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectMCPResponse)
	err := c.cc.Invoke(ctx, NexusService_ConnectMCP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nexusServiceClient) DisconnectMCP(ctx context.Context, in *DisconnectMCPRequest, opts ...grpc.CallOption) (*DisconnectMCPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisconnectMCPResponse)
	err := c.cc.Invoke(ctx, NexusService_DisconnectMCP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nexusServiceClient) GetModels(ctx context.Context, in *GetModelsRequest, opts ...grpc.CallOption) (*GetModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetModelsResponse)
	err := c.cc.Invoke(ctx, NexusService_GetModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nexusServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, NexusService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NexusServiceServer is the server API for NexusService service.
// All implementations must embed UnimplementedNexusServiceServer
// for forward compatibility.
//
// NexusService est le service principal pour les interactions avec le moteur IA
type NexusServiceServer interface {
	// Exécute une requête simple (non-streaming)
	Query(context.Context, *QueryRequest) (*QueryResponse, error)
	// Exécute une requête en mode streaming (pour les réponses longues)
	QueryStream(*QueryRequest, grpc.ServerStreamingServer[QueryResponse]) error
	// Liste tous les skills disponibles
	ListSkills(context.Context, *ListSkillsRequest) (*ListSkillsResponse, error)
	// Retourne les détails d'un skill spécifique
	GetSkillDetails(context.Context, *GetSkillDetailsRequest) (*GetSkillDetailsResponse, error)
	// Liste les serveurs MCP connectés
	ListMCP(context.Context, *ListMCPRequest) (*ListMCPResponse, error)
	// Connecte à un serveur MCP
	ConnectMCP(context.Context, *ConnectMCPRequest) (*ConnectMCPResponse, error)
	// Déconnecte un serveur MCP
	DisconnectMCP(context.Context, *DisconnectMCPRequest) (*DisconnectMCPResponse, error)
	// Liste les modèles disponibles
	GetModels(context.Context, *GetModelsRequest) (*GetModelsResponse, error)
	// Health check pour le monitoring
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedNexusServiceServer()
}

// UnimplementedNexusServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNexusServiceServer struct{}

func (UnimplementedNexusServiceServer) Query(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedNexusServiceServer) QueryStream(*QueryRequest, grpc.ServerStreamingServer[QueryResponse]) error {
	return status.Error(codes.Unimplemented, "method QueryStream not implemented")
}
func (UnimplementedNexusServiceServer) ListSkills(context.Context, *ListSkillsRequest) (*ListSkillsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSkills not implemented")
}
func (UnimplementedNexusServiceServer) GetSkillDetails(context.Context, *GetSkillDetailsRequest) (*GetSkillDetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSkillDetails not implemented")
}
func (UnimplementedNexusServiceServer) ListMCP(context.Context, *ListMCPRequest) (*ListMCPResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMCP not implemented")
}
func (UnimplementedNexusServiceServer) ConnectMCP(context.Context, *ConnectMCPRequest) (*ConnectMCPResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConnectMCP not implemented")
}
func (UnimplementedNexusServiceServer) DisconnectMCP(context.Context, *DisconnectMCPRequest) (*DisconnectMCPResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DisconnectMCP not implemented")
}
func (UnimplementedNexusServiceServer) GetModels(context.Context, *GetModelsRequest) (*GetModelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetModels not implemented")
}
func (UnimplementedNexusServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedNexusServiceServer) mustEmbedUnimplementedNexusServiceServer() {}
func (UnimplementedNexusServiceServer) testEmbeddedByValue()                      {}

// UnsafeNexusServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NexusServiceServer will
// result in compilation errors.
type UnsafeNexusServiceServer interface {
	mustEmbedUnimplementedNexusServiceServer()
}

func RegisterNexusServiceServer(s grpc.ServiceRegistrar, srv NexusServiceServer) {
	// If the following call panics, it indicates UnimplementedNexusServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NexusService_ServiceDesc, srv)
}

func _NexusService_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NexusServiceServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NexusService_Query_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NexusServiceServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NexusService_QueryStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(QueryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NexusServiceServer).QueryStream(m, &grpc.GenericServerStream[QueryRequest, QueryResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NexusService_QueryStreamServer = grpc.ServerStreamingServer[QueryResponse]

func _NexusService_ListSkills_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSkillsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NexusServiceServer).ListSkills(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NexusService_ListSkills_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NexusServiceServer).ListSkills(ctx, req.(*ListSkillsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NexusService_GetSkillDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSkillDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NexusServiceServer).GetSkillDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NexusService_GetSkillDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NexusServiceServer).GetSkillDetails(ctx, req.(*GetSkillDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NexusService_ListMCP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMCPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NexusServiceServer).ListMCP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NexusService_ListMCP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NexusServiceServer).ListMCP(ctx, req.(*ListMCPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NexusService_ConnectMCP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectMCPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NexusServiceServer).ConnectMCP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NexusService_ConnectMCP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NexusServiceServer).ConnectMCP(ctx, req.(*ConnectMCPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NexusService_DisconnectMCP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectMCPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NexusServiceServer).DisconnectMCP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NexusService_DisconnectMCP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NexusServiceServer).DisconnectMCP(ctx, req.(*DisconnectMCPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NexusService_GetModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NexusServiceServer).GetModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NexusService_GetModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NexusServiceServer).GetModels(ctx, req.(*GetModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NexusService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NexusServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NexusService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NexusServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NexusService_ServiceDesc is the grpc.ServiceDesc for NexusService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NexusService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nexus.NexusService",
	HandlerType: (*NexusServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Query",
			Handler:    _NexusService_Query_Handler,
		},
		{
			MethodName: "ListSkills",
			Handler:    _NexusService_ListSkills_Handler,
		},
		{
			MethodName: "GetSkillDetails",
			Handler:    _NexusService_GetSkillDetails_Handler,
		},
		{
			MethodName: "ListMCP",
			Handler:    _NexusService_ListMCP_Handler,
		},
		{
			MethodName: "ConnectMCP",
			Handler:    _NexusService_ConnectMCP_Handler,
		},
		{
			MethodName: "DisconnectMCP",
			Handler:    _NexusService_DisconnectMCP_Handler,
		},
		{
			MethodName: "GetModels",
			Handler:    _NexusService_GetModels_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _NexusService_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "QueryStream",
			Handler:       _NexusService_QueryStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "nexus.proto",
}

const (
	FileService_Read_FullMethodName  = "/nexus.FileService/Read"
	FileService_Write_FullMethodName = "/nexus.FileService/Write"
	FileService_Edit_FullMethodName  = "/nexus.FileService/Edit"
	FileService_Glob_FullMethodName  = "/nexus.FileService/Glob"
	FileService_Grep_FullMethodName  = "/nexus.FileService/Grep"
)

// FileServiceClient is the client API for FileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service pour les opérations de fichiers
type FileServiceClient interface {
	Read(ctx context.Context, in *FileReadRequest, opts ...grpc.CallOption) (*FileReadResponse, error)
	Write(ctx context.Context, in *FileWriteRequest, opts ...grpc.CallOption) (*FileWriteResponse, error)
	Edit(ctx context.Context, in *FileEditRequest, opts ...grpc.CallOption) (*FileEditResponse, error)
	Glob(ctx context.Context, in *FileGlobRequest, opts ...grpc.CallOption) (*FileGlobResponse, error)
	Grep(ctx context.Context, in *FileGrepRequest, opts ...grpc.CallOption) (*FileGrepResponse, error)
}

type fileServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFileServiceClient(cc grpc.ClientConnInterface) FileServiceClient {
	return &fileServiceClient{cc}
}

func (c *fileServiceClient) Read(ctx context.Context, in *FileReadRequest, opts ...grpc.CallOption) (*FileReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileReadResponse)
	err := c.cc.Invoke(ctx, FileService_Read_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) Write(ctx context.Context, in *FileWriteRequest, opts ...grpc.CallOption) (*FileWriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileWriteResponse)
	err := c.cc.Invoke(ctx, FileService_Write_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) Edit(ctx context.Context, in *FileEditRequest, opts ...grpc.CallOption) (*FileEditResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileEditResponse)
	err := c.cc.Invoke(ctx, FileService_Edit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) Glob(ctx context.Context, in *FileGlobRequest, opts ...grpc.CallOption) (*FileGlobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileGlobResponse)
	err := c.cc.Invoke(ctx, FileService_Glob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) Grep(ctx context.Context, in *FileGrepRequest, opts ...grpc.CallOption) (*FileGrepResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileGrepResponse)
	err := c.cc.Invoke(ctx, FileService_Grep_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileServiceServer is the server API for FileService service.
// All implementations must embed UnimplementedFileServiceServer
// for forward compatibility.
//
// Service pour les opérations de fichiers
type FileServiceServer interface {
	Read(context.Context, *FileReadRequest) (*FileReadResponse, error)
	Write(context.Context, *FileWriteRequest) (*FileWriteResponse, error)
	Edit(context.Context, *FileEditRequest) (*FileEditResponse, error)
	Glob(context.Context, *FileGlobRequest) (*FileGlobResponse, error)
	Grep(context.Context, *FileGrepRequest) (*FileGrepResponse, error)
	mustEmbedUnimplementedFileServiceServer()
}

// UnimplementedFileServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFileServiceServer struct{}

func (UnimplementedFileServiceServer) Read(context.Context, *FileReadRequest) (*FileReadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedFileServiceServer) Write(context.Context, *FileWriteRequest) (*FileWriteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Write not implemented")
}
func (UnimplementedFileServiceServer) Edit(context.Context, *FileEditRequest) (*FileEditResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Edit not implemented")
}
func (UnimplementedFileServiceServer) Glob(context.Context, *FileGlobRequest) (*FileGlobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Glob not implemented")
}
func (UnimplementedFileServiceServer) Grep(context.Context, *FileGrepRequest) (*FileGrepResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Grep not implemented")
}
func (UnimplementedFileServiceServer) mustEmbedUnimplementedFileServiceServer() {}
func (UnimplementedFileServiceServer) testEmbeddedByValue()                     {}

// UnsafeFileServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileServiceServer will
// result in compilation errors.
type UnsafeFileServiceServer interface {
	mustEmbedUnimplementedFileServiceServer()
}

func RegisterFileServiceServer(s grpc.ServiceRegistrar, srv FileServiceServer) {
	// If the following call panics, it indicates UnimplementedFileServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FileService_ServiceDesc, srv)
}

func _FileService_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_Read_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).Read(ctx, req.(*FileReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_Write_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileWriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).Write(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_Write_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).Write(ctx, req.(*FileWriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_Edit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileEditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).Edit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_Edit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).Edit(ctx, req.(*FileEditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_Glob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileGlobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).Glob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_Glob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).Glob(ctx, req.(*FileGlobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_Grep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileGrepRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).Grep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_Grep_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).Grep(ctx, req.(*FileGrepRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FileService_ServiceDesc is the grpc.ServiceDesc for FileService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nexus.FileService",
	HandlerType: (*FileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Read",
			Handler:    _FileService_Read_Handler,
		},
		{
			MethodName: "Write",
			Handler:    _FileService_Write_Handler,
		},
		{
			MethodName: "Edit",
			Handler:    _FileService_Edit_Handler,
		},
		{
			MethodName: "Glob",
			Handler:    _FileService_Glob_Handler,
		},
		{
			MethodName: "Grep",
			Handler:    _FileService_Grep_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nexus.proto",
}

const (
	SystemService_Bash_FullMethodName          = "/nexus.SystemService/Bash"
	SystemService_GetSystemInfo_FullMethodName = "/nexus.SystemService/GetSystemInfo"
)

// SystemServiceClient is the client API for SystemService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service pour les opérations système
type SystemServiceClient interface {
	Bash(ctx context.Context, in *BashRequest, opts ...grpc.CallOption) (*BashResponse, error)
	GetSystemInfo(ctx context.Context, in *SystemInfoRequest, opts ...grpc.CallOption) (*SystemInfoResponse, error)
}

type systemServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSystemServiceClient(cc grpc.ClientConnInterface) SystemServiceClient {
	return &systemServiceClient{cc}
}

func (c *systemServiceClient) Bash(ctx context.Context, in *BashRequest, opts ...grpc.CallOption) (*BashResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BashResponse)
	err := c.cc.Invoke(ctx, SystemService_Bash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) GetSystemInfo(ctx context.Context, in *SystemInfoRequest, opts ...grpc.CallOption) (*SystemInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SystemInfoResponse)
	err := c.cc.Invoke(ctx, SystemService_GetSystemInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SystemServiceServer is the server API for SystemService service.
// All implementations must embed UnimplementedSystemServiceServer
// for forward compatibility.
//
// Service pour les opérations système
type SystemServiceServer interface {
	Bash(context.Context, *BashRequest) (*BashResponse, error)
	GetSystemInfo(context.Context, *SystemInfoRequest) (*SystemInfoResponse, error)
	mustEmbedUnimplementedSystemServiceServer()
}

// UnimplementedSystemServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSystemServiceServer struct{}

func (UnimplementedSystemServiceServer) Bash(context.Context, *BashRequest) (*BashResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Bash not implemented")
}
func (UnimplementedSystemServiceServer) GetSystemInfo(context.Context, *SystemInfoRequest) (*SystemInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSystemInfo not implemented")
}
func (UnimplementedSystemServiceServer) mustEmbedUnimplementedSystemServiceServer() {}
func (UnimplementedSystemServiceServer) testEmbeddedByValue()                       {}

// UnsafeSystemServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SystemServiceServer will
// result in compilation errors.
type UnsafeSystemServiceServer interface {
	mustEmbedUnimplementedSystemServiceServer()
}

func RegisterSystemServiceServer(s grpc.ServiceRegistrar, srv SystemServiceServer) {
	// If the following call panics, it indicates UnimplementedSystemServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SystemService_ServiceDesc, srv)
}

func _SystemService_Bash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).Bash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemService_Bash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).Bash(ctx, req.(*BashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_GetSystemInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SystemInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).GetSystemInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemService_GetSystemInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).GetSystemInfo(ctx, req.(*SystemInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SystemService_ServiceDesc is the grpc.ServiceDesc for SystemService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SystemService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nexus.SystemService",
	HandlerType: (*SystemServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Bash",
			Handler:    _SystemService_Bash_Handler,
		},
		{
			MethodName: "GetSystemInfo",
			Handler:    _SystemService_GetSystemInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nexus.proto",
}
