package archtest

import (
	"go/ast"
	"go/parser"
	"go/token"
	"io/fs"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"testing"
)

// Every exported function, method of an exported type and type of pkg/ (the public API) has a doc comment, as AGENTS.md asks: a public
// API without them cannot be used without reading the code. Files generated by a tool (protobuf) are not looked at.
func TestPublicAPIHasDocComments(t *testing.T) {
	root := filepath.Join("..", "..")
	var missing []string
	err := filepath.WalkDir(filepath.Join(root, "pkg"), func(path string, d fs.DirEntry, err error) error {
		if err != nil || d.IsDir() || !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
			return err
		}
		fset := token.NewFileSet()
		file, perr := parser.ParseFile(fset, path, nil, parser.ParseComments)
		if perr != nil {
			return perr
		}
		if isGenerated(file) {
			return nil
		}
		rel, rerr := filepath.Rel(root, path)
		if rerr != nil {
			return rerr
		}
		rel = filepath.ToSlash(rel)
		for _, decl := range file.Decls {
			switch x := decl.(type) {
			case *ast.FuncDecl:
				if !x.Name.IsExported() || x.Doc != nil {
					continue
				}
				name := x.Name.Name
				if x.Recv != nil {
					recv, ok := exportedReceiverName(x.Recv)
					if !ok {
						continue
					}
					name = recv + "." + name
				}
				missing = append(missing, rel+":"+strconv.Itoa(fset.Position(x.Pos()).Line)+" "+name)
			case *ast.GenDecl:
				for _, spec := range x.Specs {
					if ts, ok := spec.(*ast.TypeSpec); ok && ts.Name.IsExported() && x.Doc == nil && ts.Doc == nil {
						missing = append(missing, rel+":"+strconv.Itoa(fset.Position(ts.Pos()).Line)+" type "+ts.Name.Name)
					}
				}
			}
		}
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
	sort.Strings(missing)
	for _, m := range missing {
		t.Errorf("%s has no doc comment: every exported symbol of pkg/ needs one (AGENTS.md)", m)
	}
}

func isGenerated(file *ast.File) bool {
	for _, group := range file.Comments {
		for _, c := range group.List {
			if strings.Contains(c.Text, "Code generated") && strings.Contains(c.Text, "DO NOT EDIT") {
				return true
			}
		}
	}
	return false
}

// exportedReceiverName returns the name of the receiver type and whether that type is exported.
func exportedReceiverName(recv *ast.FieldList) (string, bool) {
	if recv == nil || len(recv.List) == 0 {
		return "", false
	}
	typ := recv.List[0].Type
	if star, ok := typ.(*ast.StarExpr); ok {
		typ = star.X
	}
	if idx, ok := typ.(*ast.IndexExpr); ok {
		typ = idx.X
	}
	id, ok := typ.(*ast.Ident)
	if !ok || !id.IsExported() {
		return "", false
	}
	return id.Name, true
}
