// ============================================================================
// Seshat - Protocole gRPC
// ============================================================================
//
// Ce fichier définit les services gRPC pour l'API Seshat.
// À compiler avec: protoc --go_out=. --go-grpc_out=. seshat.proto
//
// ============================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: pkg/grpc/proto/seshat.proto

package seshat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Requête pour exécuter une requête IA
type QueryRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Prompt    string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`                        // Le prompt à exécuter
	Model     string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`                          // Modèle à utiliser (ex: "claude-3-5-sonnet-20241022")
	Tools     []string               `protobuf:"bytes,3,rep,name=tools,proto3" json:"tools,omitempty"`                          // Liste des tools à activer
	Stream    bool                   `protobuf:"varint,4,opt,name=stream,proto3" json:"stream,omitempty"`                       // Mode streaming
	ContextId string                 `protobuf:"bytes,5,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"` // ID de contexte pour la continuité de conversation
	// Paramètres optionnels
	Temperature   float32 `protobuf:"fixed32,10,opt,name=temperature,proto3" json:"temperature,omitempty"`             // Temperature (0.0 - 1.0)
	MaxTokens     int32   `protobuf:"varint,11,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"` // Nombre max de tokens en sortie
	ApiKey        string  `protobuf:"bytes,12,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`           // Clé API ou bearer token OAuth explicite pour cette requête
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_seshat_proto_rawDescGZIP(), []int{0}
}

func (x *QueryRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *QueryRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *QueryRequest) GetTools() []string {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *QueryRequest) GetStream() bool {
	if x != nil {
		return x.Stream
	}
	return false
}

func (x *QueryRequest) GetContextId() string {
	if x != nil {
		return x.ContextId
	}
	return ""
}

func (x *QueryRequest) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *QueryRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *QueryRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

// Requête pour lister les skills
type ListSkillsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceFilter  string                 `protobuf:"bytes,1,opt,name=source_filter,json=sourceFilter,proto3" json:"source_filter,omitempty"` // Filter par source: "all", "bundled", "mcp", "file"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSkillsRequest) Reset() {
	*x = ListSkillsRequest{}
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSkillsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSkillsRequest) ProtoMessage() {}

func (x *ListSkillsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSkillsRequest.ProtoReflect.Descriptor instead.
func (*ListSkillsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_seshat_proto_rawDescGZIP(), []int{1}
}

func (x *ListSkillsRequest) GetSourceFilter() string {
	if x != nil {
		return x.SourceFilter
	}
	return ""
}

// Requête pour obtenir les détails d'un skill
type GetSkillDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // Nom du skill
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSkillDetailsRequest) Reset() {
	*x = GetSkillDetailsRequest{}
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSkillDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSkillDetailsRequest) ProtoMessage() {}

func (x *GetSkillDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSkillDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetSkillDetailsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_seshat_proto_rawDescGZIP(), []int{2}
}

func (x *GetSkillDetailsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Requête pour lister les serveurs MCP
type ListMCPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMCPRequest) Reset() {
	*x = ListMCPRequest{}
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMCPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMCPRequest) ProtoMessage() {}

func (x *ListMCPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMCPRequest.ProtoReflect.Descriptor instead.
func (*ListMCPRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_seshat_proto_rawDescGZIP(), []int{3}
}

// Requête pour connecter un serveur MCP
type ConnectMCPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                                                         // Nom du serveur
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`                                                                         // Type: "stdio", "http", "sse", "ws"
	Command       string                 `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`                                                                   // Commande (pour stdio)
	Args          []string               `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty"`                                                                         // Arguments de la commande
	Url           string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`                                                                           // URL (pour http/sse/ws)
	Env           map[string]string      `protobuf:"bytes,6,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Variables d'environnement
	Timeout       int32                  `protobuf:"varint,7,opt,name=timeout,proto3" json:"timeout,omitempty"`                                                                  // Timeout en secondes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectMCPRequest) Reset() {
	*x = ConnectMCPRequest{}
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectMCPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectMCPRequest) ProtoMessage() {}

func (x *ConnectMCPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectMCPRequest.ProtoReflect.Descriptor instead.
func (*ConnectMCPRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_seshat_proto_rawDescGZIP(), []int{4}
}

func (x *ConnectMCPRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConnectMCPRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ConnectMCPRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ConnectMCPRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ConnectMCPRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ConnectMCPRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ConnectMCPRequest) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

// Requête pour déconnecter un serveur MCP
type DisconnectMCPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // Nom du serveur à déconnecter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectMCPRequest) Reset() {
	*x = DisconnectMCPRequest{}
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectMCPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectMCPRequest) ProtoMessage() {}

func (x *DisconnectMCPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectMCPRequest.ProtoReflect.Descriptor instead.
func (*DisconnectMCPRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_seshat_proto_rawDescGZIP(), []int{5}
}

func (x *DisconnectMCPRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Requête pour lister les modèles
type GetModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelsRequest) Reset() {
	*x = GetModelsRequest{}
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelsRequest) ProtoMessage() {}

func (x *GetModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelsRequest.ProtoReflect.Descriptor instead.
func (*GetModelsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_seshat_proto_rawDescGZIP(), []int{6}
}

// Requête pour health check
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_seshat_proto_rawDescGZIP(), []int{7}
}

// Réponse à une requête Query
type QueryResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Content    string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`                         // Contenu de la réponse
	Model      string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`                             // Modèle utilisé
	TokenUsage *TokenUsage            `protobuf:"bytes,3,opt,name=token_usage,json=tokenUsage,proto3" json:"token_usage,omitempty"` // Utilisation des tokens
	// Métadonnées additionnelles
	ConversationId string        `protobuf:"bytes,10,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"` // ID de conversation
	Stopped        bool          `protobuf:"varint,11,opt,name=stopped,proto3" json:"stopped,omitempty"`                                    // Si la réponse a été coupée
	ItemType       string        `protobuf:"bytes,12,opt,name=item_type,json=itemType,proto3" json:"item_type,omitempty"`                   // "chunk", "runtime_event", "final"
	Chunk          *ChunkDelta   `protobuf:"bytes,13,opt,name=chunk,proto3" json:"chunk,omitempty"`                                         // Détails structurés pour un delta streamé
	RuntimeEvent   *RuntimeEvent `protobuf:"bytes,14,opt,name=runtime_event,json=runtimeEvent,proto3" json:"runtime_event,omitempty"`       // Événement runtime structuré
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_seshat_proto_rawDescGZIP(), []int{8}
}

func (x *QueryResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *QueryResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *QueryResponse) GetTokenUsage() *TokenUsage {
	if x != nil {
		return x.TokenUsage
	}
	return nil
}

func (x *QueryResponse) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *QueryResponse) GetStopped() bool {
	if x != nil {
		return x.Stopped
	}
	return false
}

func (x *QueryResponse) GetItemType() string {
	if x != nil {
		return x.ItemType
	}
	return ""
}

func (x *QueryResponse) GetChunk() *ChunkDelta {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *QueryResponse) GetRuntimeEvent() *RuntimeEvent {
	if x != nil {
		return x.RuntimeEvent
	}
	return nil
}

// Delta de réponse streamé
type ChunkDelta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	DeltaType     string                 `protobuf:"bytes,2,opt,name=delta_type,json=deltaType,proto3" json:"delta_type,omitempty"`
	Delta         string                 `protobuf:"bytes,3,opt,name=delta,proto3" json:"delta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkDelta) Reset() {
	*x = ChunkDelta{}
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkDelta) ProtoMessage() {}

func (x *ChunkDelta) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkDelta.ProtoReflect.Descriptor instead.
func (*ChunkDelta) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_seshat_proto_rawDescGZIP(), []int{9}
}

func (x *ChunkDelta) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ChunkDelta) GetDeltaType() string {
	if x != nil {
		return x.DeltaType
	}
	return ""
}

func (x *ChunkDelta) GetDelta() string {
	if x != nil {
		return x.Delta
	}
	return ""
}

// Événement runtime structuré du moteur
type RuntimeEvent struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Type                string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	SessionId           string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TurnId              string                 `protobuf:"bytes,3,opt,name=turn_id,json=turnId,proto3" json:"turn_id,omitempty"`
	TurnNumber          int32                  `protobuf:"varint,4,opt,name=turn_number,json=turnNumber,proto3" json:"turn_number,omitempty"`
	Timestamp           string                 `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	StopReason          string                 `protobuf:"bytes,6,opt,name=stop_reason,json=stopReason,proto3" json:"stop_reason,omitempty"`
	TokenUsage          *TokenUsage            `protobuf:"bytes,7,opt,name=token_usage,json=tokenUsage,proto3" json:"token_usage,omitempty"`
	Chunk               *ChunkDelta            `protobuf:"bytes,8,opt,name=chunk,proto3" json:"chunk,omitempty"`
	ToolName            string                 `protobuf:"bytes,9,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	ToolStage           string                 `protobuf:"bytes,10,opt,name=tool_stage,json=toolStage,proto3" json:"tool_stage,omitempty"`
	ToolMessage         string                 `protobuf:"bytes,11,opt,name=tool_message,json=toolMessage,proto3" json:"tool_message,omitempty"`
	ToolPercentComplete float32                `protobuf:"fixed32,12,opt,name=tool_percent_complete,json=toolPercentComplete,proto3" json:"tool_percent_complete,omitempty"`
	Error               string                 `protobuf:"bytes,13,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RuntimeEvent) Reset() {
	*x = RuntimeEvent{}
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeEvent) ProtoMessage() {}

func (x *RuntimeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeEvent.ProtoReflect.Descriptor instead.
func (*RuntimeEvent) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_seshat_proto_rawDescGZIP(), []int{10}
}

func (x *RuntimeEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RuntimeEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RuntimeEvent) GetTurnId() string {
	if x != nil {
		return x.TurnId
	}
	return ""
}

func (x *RuntimeEvent) GetTurnNumber() int32 {
	if x != nil {
		return x.TurnNumber
	}
	return 0
}

func (x *RuntimeEvent) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *RuntimeEvent) GetStopReason() string {
	if x != nil {
		return x.StopReason
	}
	return ""
}

func (x *RuntimeEvent) GetTokenUsage() *TokenUsage {
	if x != nil {
		return x.TokenUsage
	}
	return nil
}

func (x *RuntimeEvent) GetChunk() *ChunkDelta {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *RuntimeEvent) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *RuntimeEvent) GetToolStage() string {
	if x != nil {
		return x.ToolStage
	}
	return ""
}

func (x *RuntimeEvent) GetToolMessage() string {
	if x != nil {
		return x.ToolMessage
	}
	return ""
}

func (x *RuntimeEvent) GetToolPercentComplete() float32 {
	if x != nil {
		return x.ToolPercentComplete
	}
	return 0
}

func (x *RuntimeEvent) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Utilisation des tokens
type TokenUsage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InputTokens   int64                  `protobuf:"varint,1,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens  int64                  `protobuf:"varint,2,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	TotalTokens   int64                  `protobuf:"varint,3,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenUsage) Reset() {
	*x = TokenUsage{}
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenUsage) ProtoMessage() {}

func (x *TokenUsage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenUsage.ProtoReflect.Descriptor instead.
func (*TokenUsage) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_seshat_proto_rawDescGZIP(), []int{11}
}

func (x *TokenUsage) GetInputTokens() int64 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *TokenUsage) GetOutputTokens() int64 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *TokenUsage) GetTotalTokens() int64 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

// Réponse pour ListSkills
type ListSkillsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skills        []*Skill               `protobuf:"bytes,1,rep,name=skills,proto3" json:"skills,omitempty"`                            // Liste des skills
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"` // Nombre total
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSkillsResponse) Reset() {
	*x = ListSkillsResponse{}
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSkillsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSkillsResponse) ProtoMessage() {}

func (x *ListSkillsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSkillsResponse.ProtoReflect.Descriptor instead.
func (*ListSkillsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_seshat_proto_rawDescGZIP(), []int{12}
}

func (x *ListSkillsResponse) GetSkills() []*Skill {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *ListSkillsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// Informations sur un skill
type Skill struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`                          // "bundled", "file", "mcp"
	WhenToUse     string                 `protobuf:"bytes,4,opt,name=when_to_use,json=whenToUse,proto3" json:"when_to_use,omitempty"` // Quand utiliser ce skill
	AllowedTools  []string               `protobuf:"bytes,5,rep,name=allowed_tools,json=allowedTools,proto3" json:"allowed_tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Skill) Reset() {
	*x = Skill{}
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Skill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Skill) ProtoMessage() {}

func (x *Skill) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Skill.ProtoReflect.Descriptor instead.
func (*Skill) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_seshat_proto_rawDescGZIP(), []int{13}
}

func (x *Skill) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Skill) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Skill) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Skill) GetWhenToUse() string {
	if x != nil {
		return x.WhenToUse
	}
	return ""
}

func (x *Skill) GetAllowedTools() []string {
	if x != nil {
		return x.AllowedTools
	}
	return nil
}

// Réponse pour GetSkillDetails
type GetSkillDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skill         *Skill                 `protobuf:"bytes,1,opt,name=skill,proto3" json:"skill,omitempty"`   // Détails du skill
	Prompt        string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"` // Contenu du skill (si autorisé)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSkillDetailsResponse) Reset() {
	*x = GetSkillDetailsResponse{}
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSkillDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSkillDetailsResponse) ProtoMessage() {}

func (x *GetSkillDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSkillDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetSkillDetailsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_seshat_proto_rawDescGZIP(), []int{14}
}

func (x *GetSkillDetailsResponse) GetSkill() *Skill {
	if x != nil {
		return x.Skill
	}
	return nil
}

func (x *GetSkillDetailsResponse) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

// Réponse pour ListMCP
type ListMCPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Servers       []*MCPServer           `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMCPResponse) Reset() {
	*x = ListMCPResponse{}
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMCPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMCPResponse) ProtoMessage() {}

func (x *ListMCPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMCPResponse.ProtoReflect.Descriptor instead.
func (*ListMCPResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_seshat_proto_rawDescGZIP(), []int{15}
}

func (x *ListMCPResponse) GetServers() []*MCPServer {
	if x != nil {
		return x.Servers
	}
	return nil
}

func (x *ListMCPResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// Informations sur un serveur MCP
type MCPServer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                         // "connected", "disconnected", "error"
	ToolCount     int32                  `protobuf:"varint,3,opt,name=tool_count,json=toolCount,proto3" json:"tool_count,omitempty"` // Nombre de tools
	LastError     string                 `protobuf:"bytes,4,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`  // Dernière erreur si applicable
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPServer) Reset() {
	*x = MCPServer{}
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPServer) ProtoMessage() {}

func (x *MCPServer) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPServer.ProtoReflect.Descriptor instead.
func (*MCPServer) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_seshat_proto_rawDescGZIP(), []int{16}
}

func (x *MCPServer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MCPServer) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MCPServer) GetToolCount() int32 {
	if x != nil {
		return x.ToolCount
	}
	return 0
}

func (x *MCPServer) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

// Réponse pour ConnectMCP
type ConnectMCPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // Message d'erreur si échec
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectMCPResponse) Reset() {
	*x = ConnectMCPResponse{}
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectMCPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectMCPResponse) ProtoMessage() {}

func (x *ConnectMCPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectMCPResponse.ProtoReflect.Descriptor instead.
func (*ConnectMCPResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_seshat_proto_rawDescGZIP(), []int{17}
}

func (x *ConnectMCPResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConnectMCPResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Réponse pour DisconnectMCP
type DisconnectMCPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectMCPResponse) Reset() {
	*x = DisconnectMCPResponse{}
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectMCPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectMCPResponse) ProtoMessage() {}

func (x *DisconnectMCPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectMCPResponse.ProtoReflect.Descriptor instead.
func (*DisconnectMCPResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_seshat_proto_rawDescGZIP(), []int{18}
}

func (x *DisconnectMCPResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DisconnectMCPResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Réponse pour GetModels
type GetModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []*ModelInfo           `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelsResponse) Reset() {
	*x = GetModelsResponse{}
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelsResponse) ProtoMessage() {}

func (x *GetModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelsResponse.ProtoReflect.Descriptor instead.
func (*GetModelsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_seshat_proto_rawDescGZIP(), []int{19}
}

func (x *GetModelsResponse) GetModels() []*ModelInfo {
	if x != nil {
		return x.Models
	}
	return nil
}

// Informations sur un modèle
type ModelInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                 // ID du modèle (ex: "claude-3-5-sonnet-20241022")
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                             // Nom lisible (ex: "Claude 3.5 Sonnet")
	Provider      string                 `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`                     // Provider (ex: "anthropic")
	MaxTokens     int32                  `protobuf:"varint,4,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"` // Token max en entrée
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelInfo) Reset() {
	*x = ModelInfo{}
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelInfo) ProtoMessage() {}

func (x *ModelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelInfo.ProtoReflect.Descriptor instead.
func (*ModelInfo) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_seshat_proto_rawDescGZIP(), []int{20}
}

func (x *ModelInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ModelInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModelInfo) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ModelInfo) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

// Réponse pour HealthCheck
type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`   // "ok", "degraded", "down"
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"` // Version du serveur
	Uptime        string                 `protobuf:"bytes,3,opt,name=uptime,proto3" json:"uptime,omitempty"`   // Durée de fonctionnement
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_seshat_proto_rawDescGZIP(), []int{21}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthCheckResponse) GetUptime() string {
	if x != nil {
		return x.Uptime
	}
	return ""
}

type FileReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileReadRequest) Reset() {
	*x = FileReadRequest{}
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileReadRequest) ProtoMessage() {}

func (x *FileReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileReadRequest.ProtoReflect.Descriptor instead.
func (*FileReadRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_seshat_proto_rawDescGZIP(), []int{22}
}

func (x *FileReadRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileReadRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *FileReadRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type FileReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Error         bool                   `protobuf:"varint,2,opt,name=error,proto3" json:"error,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileReadResponse) Reset() {
	*x = FileReadResponse{}
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileReadResponse) ProtoMessage() {}

func (x *FileReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileReadResponse.ProtoReflect.Descriptor instead.
func (*FileReadResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_seshat_proto_rawDescGZIP(), []int{23}
}

func (x *FileReadResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *FileReadResponse) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

func (x *FileReadResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type FileWriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileWriteRequest) Reset() {
	*x = FileWriteRequest{}
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileWriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileWriteRequest) ProtoMessage() {}

func (x *FileWriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileWriteRequest.ProtoReflect.Descriptor instead.
func (*FileWriteRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_seshat_proto_rawDescGZIP(), []int{24}
}

func (x *FileWriteRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileWriteRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type FileWriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileWriteResponse) Reset() {
	*x = FileWriteResponse{}
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileWriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileWriteResponse) ProtoMessage() {}

func (x *FileWriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileWriteResponse.ProtoReflect.Descriptor instead.
func (*FileWriteResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_seshat_proto_rawDescGZIP(), []int{25}
}

func (x *FileWriteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FileWriteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type FileEditRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	OldString     string                 `protobuf:"bytes,2,opt,name=old_string,json=oldString,proto3" json:"old_string,omitempty"`
	NewString     string                 `protobuf:"bytes,3,opt,name=new_string,json=newString,proto3" json:"new_string,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileEditRequest) Reset() {
	*x = FileEditRequest{}
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileEditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileEditRequest) ProtoMessage() {}

func (x *FileEditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileEditRequest.ProtoReflect.Descriptor instead.
func (*FileEditRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_seshat_proto_rawDescGZIP(), []int{26}
}

func (x *FileEditRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileEditRequest) GetOldString() string {
	if x != nil {
		return x.OldString
	}
	return ""
}

func (x *FileEditRequest) GetNewString() string {
	if x != nil {
		return x.NewString
	}
	return ""
}

type FileEditResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileEditResponse) Reset() {
	*x = FileEditResponse{}
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileEditResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileEditResponse) ProtoMessage() {}

func (x *FileEditResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileEditResponse.ProtoReflect.Descriptor instead.
func (*FileEditResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_seshat_proto_rawDescGZIP(), []int{27}
}

func (x *FileEditResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FileEditResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type FileGlobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pattern       string                 `protobuf:"bytes,1,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileGlobRequest) Reset() {
	*x = FileGlobRequest{}
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileGlobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileGlobRequest) ProtoMessage() {}

func (x *FileGlobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileGlobRequest.ProtoReflect.Descriptor instead.
func (*FileGlobRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_seshat_proto_rawDescGZIP(), []int{28}
}

func (x *FileGlobRequest) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *FileGlobRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type FileGlobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []string               `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileGlobResponse) Reset() {
	*x = FileGlobResponse{}
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileGlobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileGlobResponse) ProtoMessage() {}

func (x *FileGlobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileGlobResponse.ProtoReflect.Descriptor instead.
func (*FileGlobResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_seshat_proto_rawDescGZIP(), []int{29}
}

func (x *FileGlobResponse) GetFiles() []string {
	if x != nil {
		return x.Files
	}
	return nil
}

type FileGrepRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pattern       string                 `protobuf:"bytes,1,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Recursive     bool                   `protobuf:"varint,3,opt,name=recursive,proto3" json:"recursive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileGrepRequest) Reset() {
	*x = FileGrepRequest{}
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileGrepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileGrepRequest) ProtoMessage() {}

func (x *FileGrepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileGrepRequest.ProtoReflect.Descriptor instead.
func (*FileGrepRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_seshat_proto_rawDescGZIP(), []int{30}
}

func (x *FileGrepRequest) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *FileGrepRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileGrepRequest) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

type FileGrepResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matches       []*GrepMatch           `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileGrepResponse) Reset() {
	*x = FileGrepResponse{}
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileGrepResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileGrepResponse) ProtoMessage() {}

func (x *FileGrepResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileGrepResponse.ProtoReflect.Descriptor instead.
func (*FileGrepResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_seshat_proto_rawDescGZIP(), []int{31}
}

func (x *FileGrepResponse) GetMatches() []*GrepMatch {
	if x != nil {
		return x.Matches
	}
	return nil
}

type GrepMatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          string                 `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	Line          int32                  `protobuf:"varint,2,opt,name=line,proto3" json:"line,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrepMatch) Reset() {
	*x = GrepMatch{}
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrepMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrepMatch) ProtoMessage() {}

func (x *GrepMatch) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrepMatch.ProtoReflect.Descriptor instead.
func (*GrepMatch) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_seshat_proto_rawDescGZIP(), []int{32}
}

func (x *GrepMatch) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *GrepMatch) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *GrepMatch) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type BashRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Cwd           string                 `protobuf:"bytes,2,opt,name=cwd,proto3" json:"cwd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BashRequest) Reset() {
	*x = BashRequest{}
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BashRequest) ProtoMessage() {}

func (x *BashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BashRequest.ProtoReflect.Descriptor instead.
func (*BashRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_seshat_proto_rawDescGZIP(), []int{33}
}

func (x *BashRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *BashRequest) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

type BashResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        string                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	ExitCode      int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BashResponse) Reset() {
	*x = BashResponse{}
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BashResponse) ProtoMessage() {}

func (x *BashResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BashResponse.ProtoReflect.Descriptor instead.
func (*BashResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_seshat_proto_rawDescGZIP(), []int{34}
}

func (x *BashResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *BashResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *BashResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SystemInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemInfoRequest) Reset() {
	*x = SystemInfoRequest{}
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfoRequest) ProtoMessage() {}

func (x *SystemInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfoRequest.ProtoReflect.Descriptor instead.
func (*SystemInfoRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_seshat_proto_rawDescGZIP(), []int{35}
}

type SystemInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Os            string                 `protobuf:"bytes,1,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,2,opt,name=arch,proto3" json:"arch,omitempty"`
	CpuCount      int32                  `protobuf:"varint,3,opt,name=cpu_count,json=cpuCount,proto3" json:"cpu_count,omitempty"`
	MemoryTotal   int64                  `protobuf:"varint,4,opt,name=memory_total,json=memoryTotal,proto3" json:"memory_total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemInfoResponse) Reset() {
	*x = SystemInfoResponse{}
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfoResponse) ProtoMessage() {}

func (x *SystemInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_seshat_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfoResponse.ProtoReflect.Descriptor instead.
func (*SystemInfoResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_seshat_proto_rawDescGZIP(), []int{36}
}

func (x *SystemInfoResponse) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *SystemInfoResponse) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *SystemInfoResponse) GetCpuCount() int32 {
	if x != nil {
		return x.CpuCount
	}
	return 0
}

func (x *SystemInfoResponse) GetMemoryTotal() int64 {
	if x != nil {
		return x.MemoryTotal
	}
	return 0
}

var File_pkg_grpc_proto_seshat_proto protoreflect.FileDescriptor

const file_pkg_grpc_proto_seshat_proto_rawDesc = "" +
	"\n" +
	"\x1bpkg/grpc/proto/seshat.proto\x12\x06seshat\"\xe3\x01\n" +
	"\fQueryRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x14\n" +
	"\x05tools\x18\x03 \x03(\tR\x05tools\x12\x16\n" +
	"\x06stream\x18\x04 \x01(\bR\x06stream\x12\x1d\n" +
	"\n" +
	"context_id\x18\x05 \x01(\tR\tcontextId\x12 \n" +
	"\vtemperature\x18\n" +
	" \x01(\x02R\vtemperature\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\v \x01(\x05R\tmaxTokens\x12\x17\n" +
	"\aapi_key\x18\f \x01(\tR\x06apiKey\"8\n" +
	"\x11ListSkillsRequest\x12#\n" +
	"\rsource_filter\x18\x01 \x01(\tR\fsourceFilter\",\n" +
	"\x16GetSkillDetailsRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x10\n" +
	"\x0eListMCPRequest\"\x83\x02\n" +
	"\x11ConnectMCPRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x04 \x03(\tR\x04args\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\x124\n" +
	"\x03env\x18\x06 \x03(\v2\".seshat.ConnectMCPRequest.EnvEntryR\x03env\x12\x18\n" +
	"\atimeout\x18\a \x01(\x05R\atimeout\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"*\n" +
	"\x14DisconnectMCPRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x12\n" +
	"\x10GetModelsRequest\"\x14\n" +
	"\x12HealthCheckRequest\"\xb9\x02\n" +
	"\rQueryResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x123\n" +
	"\vtoken_usage\x18\x03 \x01(\v2\x12.seshat.TokenUsageR\n" +
	"tokenUsage\x12'\n" +
	"\x0fconversation_id\x18\n" +
	" \x01(\tR\x0econversationId\x12\x18\n" +
	"\astopped\x18\v \x01(\bR\astopped\x12\x1b\n" +
	"\titem_type\x18\f \x01(\tR\bitemType\x12(\n" +
	"\x05chunk\x18\r \x01(\v2\x12.seshat.ChunkDeltaR\x05chunk\x129\n" +
	"\rruntime_event\x18\x0e \x01(\v2\x14.seshat.RuntimeEventR\fruntimeEvent\"U\n" +
	"\n" +
	"ChunkDelta\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"delta_type\x18\x02 \x01(\tR\tdeltaType\x12\x14\n" +
	"\x05delta\x18\x03 \x01(\tR\x05delta\"\xc2\x03\n" +
	"\fRuntimeEvent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x17\n" +
	"\aturn_id\x18\x03 \x01(\tR\x06turnId\x12\x1f\n" +
	"\vturn_number\x18\x04 \x01(\x05R\n" +
	"turnNumber\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\tR\ttimestamp\x12\x1f\n" +
	"\vstop_reason\x18\x06 \x01(\tR\n" +
	"stopReason\x123\n" +
	"\vtoken_usage\x18\a \x01(\v2\x12.seshat.TokenUsageR\n" +
	"tokenUsage\x12(\n" +
	"\x05chunk\x18\b \x01(\v2\x12.seshat.ChunkDeltaR\x05chunk\x12\x1b\n" +
	"\ttool_name\x18\t \x01(\tR\btoolName\x12\x1d\n" +
	"\n" +
	"tool_stage\x18\n" +
	" \x01(\tR\ttoolStage\x12!\n" +
	"\ftool_message\x18\v \x01(\tR\vtoolMessage\x122\n" +
	"\x15tool_percent_complete\x18\f \x01(\x02R\x13toolPercentComplete\x12\x14\n" +
	"\x05error\x18\r \x01(\tR\x05error\"w\n" +
	"\n" +
	"TokenUsage\x12!\n" +
	"\finput_tokens\x18\x01 \x01(\x03R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x02 \x01(\x03R\foutputTokens\x12!\n" +
	"\ftotal_tokens\x18\x03 \x01(\x03R\vtotalTokens\"\\\n" +
	"\x12ListSkillsResponse\x12%\n" +
	"\x06skills\x18\x01 \x03(\v2\r.seshat.SkillR\x06skills\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\x9a\x01\n" +
	"\x05Skill\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x1e\n" +
	"\vwhen_to_use\x18\x04 \x01(\tR\twhenToUse\x12#\n" +
	"\rallowed_tools\x18\x05 \x03(\tR\fallowedTools\"V\n" +
	"\x17GetSkillDetailsResponse\x12#\n" +
	"\x05skill\x18\x01 \x01(\v2\r.seshat.SkillR\x05skill\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\"_\n" +
	"\x0fListMCPResponse\x12+\n" +
	"\aservers\x18\x01 \x03(\v2\x11.seshat.MCPServerR\aservers\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"u\n" +
	"\tMCPServer\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"tool_count\x18\x03 \x01(\x05R\ttoolCount\x12\x1d\n" +
	"\n" +
	"last_error\x18\x04 \x01(\tR\tlastError\"D\n" +
	"\x12ConnectMCPResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"G\n" +
	"\x15DisconnectMCPResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\">\n" +
	"\x11GetModelsResponse\x12)\n" +
	"\x06models\x18\x01 \x03(\v2\x11.seshat.ModelInfoR\x06models\"j\n" +
	"\tModelInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x04 \x01(\x05R\tmaxTokens\"_\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06uptime\x18\x03 \x01(\tR\x06uptime\"S\n" +
	"\x0fFileReadRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"g\n" +
	"\x10FileReadResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x14\n" +
	"\x05error\x18\x02 \x01(\bR\x05error\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"@\n" +
	"\x10FileWriteRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"C\n" +
	"\x11FileWriteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"c\n" +
	"\x0fFileEditRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1d\n" +
	"\n" +
	"old_string\x18\x02 \x01(\tR\toldString\x12\x1d\n" +
	"\n" +
	"new_string\x18\x03 \x01(\tR\tnewString\"B\n" +
	"\x10FileEditResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"?\n" +
	"\x0fFileGlobRequest\x12\x18\n" +
	"\apattern\x18\x01 \x01(\tR\apattern\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"(\n" +
	"\x10FileGlobResponse\x12\x14\n" +
	"\x05files\x18\x01 \x03(\tR\x05files\"]\n" +
	"\x0fFileGrepRequest\x12\x18\n" +
	"\apattern\x18\x01 \x01(\tR\apattern\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x1c\n" +
	"\trecursive\x18\x03 \x01(\bR\trecursive\"?\n" +
	"\x10FileGrepResponse\x12+\n" +
	"\amatches\x18\x01 \x03(\v2\x11.seshat.GrepMatchR\amatches\"M\n" +
	"\tGrepMatch\x12\x12\n" +
	"\x04file\x18\x01 \x01(\tR\x04file\x12\x12\n" +
	"\x04line\x18\x02 \x01(\x05R\x04line\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"9\n" +
	"\vBashRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x10\n" +
	"\x03cwd\x18\x02 \x01(\tR\x03cwd\"Y\n" +
	"\fBashResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x13\n" +
	"\x11SystemInfoRequest\"x\n" +
	"\x12SystemInfoResponse\x12\x0e\n" +
	"\x02os\x18\x01 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x02 \x01(\tR\x04arch\x12\x1b\n" +
	"\tcpu_count\x18\x03 \x01(\x05R\bcpuCount\x12!\n" +
	"\fmemory_total\x18\x04 \x01(\x03R\vmemoryTotal2\xf5\x04\n" +
	"\rSeshatService\x124\n" +
	"\x05Query\x12\x14.seshat.QueryRequest\x1a\x15.seshat.QueryResponse\x12<\n" +
	"\vQueryStream\x12\x14.seshat.QueryRequest\x1a\x15.seshat.QueryResponse0\x01\x12C\n" +
	"\n" +
	"ListSkills\x12\x19.seshat.ListSkillsRequest\x1a\x1a.seshat.ListSkillsResponse\x12R\n" +
	"\x0fGetSkillDetails\x12\x1e.seshat.GetSkillDetailsRequest\x1a\x1f.seshat.GetSkillDetailsResponse\x12:\n" +
	"\aListMCP\x12\x16.seshat.ListMCPRequest\x1a\x17.seshat.ListMCPResponse\x12C\n" +
	"\n" +
	"ConnectMCP\x12\x19.seshat.ConnectMCPRequest\x1a\x1a.seshat.ConnectMCPResponse\x12L\n" +
	"\rDisconnectMCP\x12\x1c.seshat.DisconnectMCPRequest\x1a\x1d.seshat.DisconnectMCPResponse\x12@\n" +
	"\tGetModels\x12\x18.seshat.GetModelsRequest\x1a\x19.seshat.GetModelsResponse\x12F\n" +
	"\vHealthCheck\x12\x1a.seshat.HealthCheckRequest\x1a\x1b.seshat.HealthCheckResponse2\xb7\x02\n" +
	"\vFileService\x129\n" +
	"\x04Read\x12\x17.seshat.FileReadRequest\x1a\x18.seshat.FileReadResponse\x12<\n" +
	"\x05Write\x12\x18.seshat.FileWriteRequest\x1a\x19.seshat.FileWriteResponse\x129\n" +
	"\x04Edit\x12\x17.seshat.FileEditRequest\x1a\x18.seshat.FileEditResponse\x129\n" +
	"\x04Glob\x12\x17.seshat.FileGlobRequest\x1a\x18.seshat.FileGlobResponse\x129\n" +
	"\x04Grep\x12\x17.seshat.FileGrepRequest\x1a\x18.seshat.FileGrepResponse2\x8a\x01\n" +
	"\rSystemService\x121\n" +
	"\x04Bash\x12\x13.seshat.BashRequest\x1a\x14.seshat.BashResponse\x12F\n" +
	"\rGetSystemInfo\x12\x19.seshat.SystemInfoRequest\x1a\x1a.seshat.SystemInfoResponseB4Z2github.com/EngineerProjects/seshat/pkg/grpc/seshatb\x06proto3"

var (
	file_pkg_grpc_proto_seshat_proto_rawDescOnce sync.Once
	file_pkg_grpc_proto_seshat_proto_rawDescData []byte
)

func file_pkg_grpc_proto_seshat_proto_rawDescGZIP() []byte {
	file_pkg_grpc_proto_seshat_proto_rawDescOnce.Do(func() {
		file_pkg_grpc_proto_seshat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_grpc_proto_seshat_proto_rawDesc), len(file_pkg_grpc_proto_seshat_proto_rawDesc)))
	})
	return file_pkg_grpc_proto_seshat_proto_rawDescData
}

var file_pkg_grpc_proto_seshat_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_pkg_grpc_proto_seshat_proto_goTypes = []any{
	(*QueryRequest)(nil),            // 0: seshat.QueryRequest
	(*ListSkillsRequest)(nil),       // 1: seshat.ListSkillsRequest
	(*GetSkillDetailsRequest)(nil),  // 2: seshat.GetSkillDetailsRequest
	(*ListMCPRequest)(nil),          // 3: seshat.ListMCPRequest
	(*ConnectMCPRequest)(nil),       // 4: seshat.ConnectMCPRequest
	(*DisconnectMCPRequest)(nil),    // 5: seshat.DisconnectMCPRequest
	(*GetModelsRequest)(nil),        // 6: seshat.GetModelsRequest
	(*HealthCheckRequest)(nil),      // 7: seshat.HealthCheckRequest
	(*QueryResponse)(nil),           // 8: seshat.QueryResponse
	(*ChunkDelta)(nil),              // 9: seshat.ChunkDelta
	(*RuntimeEvent)(nil),            // 10: seshat.RuntimeEvent
	(*TokenUsage)(nil),              // 11: seshat.TokenUsage
	(*ListSkillsResponse)(nil),      // 12: seshat.ListSkillsResponse
	(*Skill)(nil),                   // 13: seshat.Skill
	(*GetSkillDetailsResponse)(nil), // 14: seshat.GetSkillDetailsResponse
	(*ListMCPResponse)(nil),         // 15: seshat.ListMCPResponse
	(*MCPServer)(nil),               // 16: seshat.MCPServer
	(*ConnectMCPResponse)(nil),      // 17: seshat.ConnectMCPResponse
	(*DisconnectMCPResponse)(nil),   // 18: seshat.DisconnectMCPResponse
	(*GetModelsResponse)(nil),       // 19: seshat.GetModelsResponse
	(*ModelInfo)(nil),               // 20: seshat.ModelInfo
	(*HealthCheckResponse)(nil),     // 21: seshat.HealthCheckResponse
	(*FileReadRequest)(nil),         // 22: seshat.FileReadRequest
	(*FileReadResponse)(nil),        // 23: seshat.FileReadResponse
	(*FileWriteRequest)(nil),        // 24: seshat.FileWriteRequest
	(*FileWriteResponse)(nil),       // 25: seshat.FileWriteResponse
	(*FileEditRequest)(nil),         // 26: seshat.FileEditRequest
	(*FileEditResponse)(nil),        // 27: seshat.FileEditResponse
	(*FileGlobRequest)(nil),         // 28: seshat.FileGlobRequest
	(*FileGlobResponse)(nil),        // 29: seshat.FileGlobResponse
	(*FileGrepRequest)(nil),         // 30: seshat.FileGrepRequest
	(*FileGrepResponse)(nil),        // 31: seshat.FileGrepResponse
	(*GrepMatch)(nil),               // 32: seshat.GrepMatch
	(*BashRequest)(nil),             // 33: seshat.BashRequest
	(*BashResponse)(nil),            // 34: seshat.BashResponse
	(*SystemInfoRequest)(nil),       // 35: seshat.SystemInfoRequest
	(*SystemInfoResponse)(nil),      // 36: seshat.SystemInfoResponse
	nil,                             // 37: seshat.ConnectMCPRequest.EnvEntry
}
var file_pkg_grpc_proto_seshat_proto_depIdxs = []int32{
	37, // 0: seshat.ConnectMCPRequest.env:type_name -> seshat.ConnectMCPRequest.EnvEntry
	11, // 1: seshat.QueryResponse.token_usage:type_name -> seshat.TokenUsage
	9,  // 2: seshat.QueryResponse.chunk:type_name -> seshat.ChunkDelta
	10, // 3: seshat.QueryResponse.runtime_event:type_name -> seshat.RuntimeEvent
	11, // 4: seshat.RuntimeEvent.token_usage:type_name -> seshat.TokenUsage
	9,  // 5: seshat.RuntimeEvent.chunk:type_name -> seshat.ChunkDelta
	13, // 6: seshat.ListSkillsResponse.skills:type_name -> seshat.Skill
	13, // 7: seshat.GetSkillDetailsResponse.skill:type_name -> seshat.Skill
	16, // 8: seshat.ListMCPResponse.servers:type_name -> seshat.MCPServer
	20, // 9: seshat.GetModelsResponse.models:type_name -> seshat.ModelInfo
	32, // 10: seshat.FileGrepResponse.matches:type_name -> seshat.GrepMatch
	0,  // 11: seshat.SeshatService.Query:input_type -> seshat.QueryRequest
	0,  // 12: seshat.SeshatService.QueryStream:input_type -> seshat.QueryRequest
	1,  // 13: seshat.SeshatService.ListSkills:input_type -> seshat.ListSkillsRequest
	2,  // 14: seshat.SeshatService.GetSkillDetails:input_type -> seshat.GetSkillDetailsRequest
	3,  // 15: seshat.SeshatService.ListMCP:input_type -> seshat.ListMCPRequest
	4,  // 16: seshat.SeshatService.ConnectMCP:input_type -> seshat.ConnectMCPRequest
	5,  // 17: seshat.SeshatService.DisconnectMCP:input_type -> seshat.DisconnectMCPRequest
	6,  // 18: seshat.SeshatService.GetModels:input_type -> seshat.GetModelsRequest
	7,  // 19: seshat.SeshatService.HealthCheck:input_type -> seshat.HealthCheckRequest
	22, // 20: seshat.FileService.Read:input_type -> seshat.FileReadRequest
	24, // 21: seshat.FileService.Write:input_type -> seshat.FileWriteRequest
	26, // 22: seshat.FileService.Edit:input_type -> seshat.FileEditRequest
	28, // 23: seshat.FileService.Glob:input_type -> seshat.FileGlobRequest
	30, // 24: seshat.FileService.Grep:input_type -> seshat.FileGrepRequest
	33, // 25: seshat.SystemService.Bash:input_type -> seshat.BashRequest
	35, // 26: seshat.SystemService.GetSystemInfo:input_type -> seshat.SystemInfoRequest
	8,  // 27: seshat.SeshatService.Query:output_type -> seshat.QueryResponse
	8,  // 28: seshat.SeshatService.QueryStream:output_type -> seshat.QueryResponse
	12, // 29: seshat.SeshatService.ListSkills:output_type -> seshat.ListSkillsResponse
	14, // 30: seshat.SeshatService.GetSkillDetails:output_type -> seshat.GetSkillDetailsResponse
	15, // 31: seshat.SeshatService.ListMCP:output_type -> seshat.ListMCPResponse
	17, // 32: seshat.SeshatService.ConnectMCP:output_type -> seshat.ConnectMCPResponse
	18, // 33: seshat.SeshatService.DisconnectMCP:output_type -> seshat.DisconnectMCPResponse
	19, // 34: seshat.SeshatService.GetModels:output_type -> seshat.GetModelsResponse
	21, // 35: seshat.SeshatService.HealthCheck:output_type -> seshat.HealthCheckResponse
	23, // 36: seshat.FileService.Read:output_type -> seshat.FileReadResponse
	25, // 37: seshat.FileService.Write:output_type -> seshat.FileWriteResponse
	27, // 38: seshat.FileService.Edit:output_type -> seshat.FileEditResponse
	29, // 39: seshat.FileService.Glob:output_type -> seshat.FileGlobResponse
	31, // 40: seshat.FileService.Grep:output_type -> seshat.FileGrepResponse
	34, // 41: seshat.SystemService.Bash:output_type -> seshat.BashResponse
	36, // 42: seshat.SystemService.GetSystemInfo:output_type -> seshat.SystemInfoResponse
	27, // [27:43] is the sub-list for method output_type
	11, // [11:27] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_pkg_grpc_proto_seshat_proto_init() }
func file_pkg_grpc_proto_seshat_proto_init() {
	if File_pkg_grpc_proto_seshat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_grpc_proto_seshat_proto_rawDesc), len(file_pkg_grpc_proto_seshat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_pkg_grpc_proto_seshat_proto_goTypes,
		DependencyIndexes: file_pkg_grpc_proto_seshat_proto_depIdxs,
		MessageInfos:      file_pkg_grpc_proto_seshat_proto_msgTypes,
	}.Build()
	File_pkg_grpc_proto_seshat_proto = out.File
	file_pkg_grpc_proto_seshat_proto_goTypes = nil
	file_pkg_grpc_proto_seshat_proto_depIdxs = nil
}
