// Package multimedia groups tools that produce or consume media:
// images (generate_image), text-to-speech (text_to_speech), and
// speech-to-text (speech_to_text). All three tools are always registered
// but IsEnabled returns false when the underlying provider is not configured,
// so they are safe to register unconditionally.
package multimedia

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/KPO-Tech/seshat/internal/image"
	tool "github.com/KPO-Tech/seshat/internal/tools/registry"
	"github.com/KPO-Tech/seshat/internal/tools/schema"
	"github.com/KPO-Tech/seshat/internal/types"
)

const (
	imageGenToolName = "generate_image"
	imageGenDesc     = `Generate an image from a text prompt using the configured image generation provider.

Returns a JSON object with:
- "provider": which provider generated the image (e.g. "openai")
- "model": the specific model used
- "image_base64": base64-encoded image data (if available)
- "image_url": public URL to the image (if available)
- "mime_type": MIME type of the image (e.g. "image/png")
- "revised_prompt": the prompt the provider actually used (may differ from input)`
)

// ImageGenTool implements the generate_image built-in tool.
type ImageGenTool struct {
	generator image.Generation
}

// NewImageGenTool creates a generate_image Tool. When generator is nil the tool
// registers normally but IsEnabled returns false, preventing execution.
func NewImageGenTool(generator image.Generation) *ImageGenTool {
	return &ImageGenTool{generator: generator}
}

func (t *ImageGenTool) Definition() tool.Definition {
	return tool.Definition{
		Name:        imageGenToolName,
		DisplayName: "Generate Image",
		Description: imageGenDesc,
		Category:    "creative",
		InputSchema: schema.FromMap(map[string]any{
			"type": "object",
			"properties": map[string]any{
				"prompt": map[string]any{
					"type":        "string",
					"description": "The text description of the image to generate. Be specific and detailed.",
				},
			},
			"required": []string{"prompt"},
		}),
		Metadata: map[string]any{"surface_profiles": []string{"mono_run"}},
	}
}

func (t *ImageGenTool) Call(ctx context.Context, input tool.CallInput, _ types.CanUseToolFn) (tool.CallResult, error) {
	if t.generator == nil {
		return tool.CallResult{Error: fmt.Errorf("generate_image: no image generation provider configured")}, nil
	}
	prompt, _ := input.Parsed["prompt"].(string)
	if prompt == "" {
		return tool.CallResult{Error: fmt.Errorf("generate_image: prompt is required")}, nil
	}
	resp, err := t.generator.GenerateImage(ctx, prompt)
	if err != nil {
		return tool.CallResult{Error: fmt.Errorf("generate_image: %w", err)}, nil
	}
	if len(resp.Images) == 0 {
		return tool.CallResult{Error: fmt.Errorf("generate_image: provider returned no images")}, nil
	}
	img := resp.Images[0]
	result := map[string]any{
		"provider":  t.generator.Provider(),
		"model":     resp.Model,
		"mime_type": img.MIMEType,
	}
	if img.ImageBase64 != "" {
		result["image_base64"] = img.ImageBase64
	}
	if img.ImageURL != "" {
		result["image_url"] = img.ImageURL
	}
	if img.RevisedPrompt != "" {
		result["revised_prompt"] = img.RevisedPrompt
	}
	encoded, err := json.Marshal(result)
	if err != nil {
		return tool.CallResult{Error: err}, nil
	}
	return tool.CallResult{Data: result, ContentType: tool.ContentTypeJSON, Content: string(encoded)}, nil
}

func (t *ImageGenTool) Description(_ context.Context) (string, error) { return imageGenDesc, nil }
func (t *ImageGenTool) ValidateInput(_ context.Context, in map[string]any) (map[string]any, error) {
	return in, nil
}
func (t *ImageGenTool) CheckPermissions(_ context.Context, _ map[string]any, _ tool.ToolUseContext) types.PermissionResult {
	return types.PermissionResult{Behavior: types.PermissionBehaviorAllow}
}
func (t *ImageGenTool) IsConcurrencySafe(_ map[string]any) bool { return true }
func (t *ImageGenTool) IsReadOnly(_ map[string]any) bool        { return true }
func (t *ImageGenTool) IsEnabled() bool                         { return t.generator != nil }
func (t *ImageGenTool) FormatResult(data any) string {
	if m, ok := data.(map[string]any); ok {
		model, _ := m["model"].(string)
		provider, _ := m["provider"].(string)
		if b64, ok := m["image_base64"].(string); ok && b64 != "" {
			return fmt.Sprintf("Image generated by %s/%s (base64, %d bytes)", provider, model, len(b64))
		}
		if u, ok := m["image_url"].(string); ok && u != "" {
			return fmt.Sprintf("Image generated by %s/%s: %s", provider, model, u)
		}
	}
	return fmt.Sprintf("%v", data)
}
func (t *ImageGenTool) BackfillInput(_ context.Context, in map[string]any) map[string]any { return in }
