//go:build ignore

// gen_provider_docs generates the provider capability matrix in docs/providers.md.
// Usage: go run scripts/gen_provider_docs.go
//
// The output replaces the "## Supported providers" section of providers.md.
// All other sections (client hierarchy, adapters, retry strategy) are preserved.
package main

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/EngineerProjects/nexus-engine/internal/providers"
	"github.com/EngineerProjects/nexus-engine/internal/types"
)

func main() {
	outPath := filepath.Join("docs", "providers.md")
	existing, err := os.ReadFile(outPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read %s: %v\n", outPath, err)
		os.Exit(1)
	}

	generated := generateProviderSection()

	// Replace everything before the first "---\n\n##" separator with the
	// freshly generated section.
	sep := "\n---\n"
	idx := strings.Index(string(existing), sep)
	var rest string
	if idx >= 0 {
		rest = string(existing)[idx:]
	}

	output := generated + rest
	if err := os.WriteFile(outPath, []byte(output), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write %s: %v\n", outPath, err)
		os.Exit(1)
	}
	fmt.Printf("Updated %s\n", outPath)
}

func generateProviderSection() string {
	allInfo := providers.AllProvidersInfo()

	// Sort providers by display name for deterministic output.
	providerOrder := []types.APIProvider{
		types.APIProviderAnthropic,
		types.APIProviderOpenAI,
		types.APIProviderMistral,
		types.APIProviderGemini,
		types.APIProviderDeepSeek,
		types.APIProviderOllama,
		types.APIProviderOpenRouter,
		types.APIProviderCodex,
		types.APIProviderZAi,
		types.APIProviderMiniMax,
		types.APIProviderBedrock,
		types.APIProviderVertex,
		types.APIProviderFoundry,
		types.APIProviderWorkersAI,
		types.APIProviderOpenCode,
	}
	// Append any provider in the registry not explicitly listed above.
	listed := make(map[types.APIProvider]bool)
	for _, p := range providerOrder {
		listed[p] = true
	}
	extras := make([]string, 0)
	for p := range allInfo {
		if !listed[p] {
			extras = append(extras, string(p))
		}
	}
	sort.Strings(extras)
	for _, e := range extras {
		providerOrder = append(providerOrder, types.APIProvider(e))
	}

	var sb strings.Builder
	sb.WriteString("# Provider System\n\n")
	sb.WriteString("<!-- AUTO-GENERATED by scripts/gen_provider_docs.go — do not edit manually -->\n\n")
	sb.WriteString("## Supported providers\n\n")

	// Capability matrix.
	sb.WriteString("| Provider ID | Service | Auth type | Vision | Prompt cache | Env var |\n")
	sb.WriteString("|---|---|---|:---:|:---:|---|\n")

	discovery := providers.DiscoverProviders(context.Background())
	envVarMap := make(map[types.APIProvider]string)
	for _, r := range discovery {
		envVarMap[r.Provider] = r.EnvVar
	}

	for _, p := range providerOrder {
		info, ok := allInfo[p]
		if !ok {
			continue
		}
		vision := "—"
		if info.SupportsCVMM {
			vision = "✓"
		}
		pc := "—"
		if info.SupportsPC {
			pc = "✓"
		}
		envVar := envVarMap[p]
		if envVar == "" {
			envVar = "—"
		}
		fmt.Fprintf(&sb, "| `%s` | %s | %s | %s | %s | `%s` |\n",
			info.Name, info.DisplayName, info.AuthType, vision, pc, envVar)
	}

	sb.WriteString("\n")
	sb.WriteString("## Model reference\n\n")

	for _, p := range providerOrder {
		info, ok := allInfo[p]
		if !ok || len(info.Models) == 0 {
			continue
		}
		fmt.Fprintf(&sb, "### %s (`%s`)\n\n", info.DisplayName, info.Name)
		sb.WriteString("| Model ID | Context | Max output | Cache | Description |\n")
		sb.WriteString("|---|---|---|:---:|---|\n")
		for _, m := range info.Models {
			pc := "—"
			if m.SupportsPC {
				pc = "✓"
			}
			ctx := formatTokens(m.ContextWindow)
			out := formatTokens(m.MaxOutput)
			desc := m.Description
			if len(desc) > 80 {
				desc = desc[:77] + "..."
			}
			fmt.Fprintf(&sb, "| `%s` | %s | %s | %s | %s |\n",
				m.Identifier, ctx, out, pc, desc)
		}
		sb.WriteString("\n")
	}

	return sb.String()
}

func formatTokens(n int) string {
	switch {
	case n >= 1_000_000:
		return fmt.Sprintf("%dM", n/1_000_000)
	case n >= 1_000:
		return fmt.Sprintf("%dK", n/1_000)
	default:
		return fmt.Sprintf("%d", n)
	}
}
