// Package imagegen provides the generate_image tool that delegates to the
// image.Generation interface. The tool is disabled when no generator is
// configured, so it is always safe to register unconditionally.
package imagegen

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/EngineerProjects/nexus-engine/internal/image"
	tool "github.com/EngineerProjects/nexus-engine/internal/tools/registry"
	"github.com/EngineerProjects/nexus-engine/internal/tools/schema"
	"github.com/EngineerProjects/nexus-engine/internal/types"
)

const (
	ToolName        = "generate_image"
	ToolDescription = `Generate an image from a text prompt using the configured image generation provider.

Returns a JSON object with:
- "provider": which provider generated the image (e.g. "openai")
- "model": the specific model used
- "image_base64": base64-encoded image data (if available)
- "image_url": public URL to the image (if available)
- "mime_type": MIME type of the image (e.g. "image/png")
- "revised_prompt": the prompt the provider actually used (may differ from input)`
)

// Tool implements the generate_image built-in tool.
type Tool struct {
	generator image.Generation
}

// NewTool creates a generate_image Tool. When generator is nil the tool
// registers normally but IsEnabled returns false, preventing execution.
func NewTool(generator image.Generation) *Tool {
	return &Tool{generator: generator}
}

// Definition implements tool.Tool.
func (t *Tool) Definition() tool.Definition {
	return tool.Definition{
		Name:        ToolName,
		DisplayName: "Generate Image",
		Description: ToolDescription,
		Category:    "creative",
		InputSchema: schema.FromMap(map[string]any{
			"type": "object",
			"properties": map[string]any{
				"prompt": map[string]any{
					"type":        "string",
					"description": "The text description of the image to generate. Be specific and detailed.",
				},
			},
			"required": []string{"prompt"},
		}),
		Metadata: map[string]any{"surface_profiles": []string{"mono_run"}},
	}
}

// Call implements tool.Tool.
func (t *Tool) Call(ctx context.Context, input tool.CallInput, permissionCheck types.CanUseToolFn) (tool.CallResult, error) {
	if t.generator == nil {
		return tool.CallResult{
			Error: fmt.Errorf("generate_image: no image generation provider configured"),
		}, nil
	}

	parsed := input.Parsed
	if parsed == nil {
		parsed = make(map[string]any)
	}

	prompt, _ := parsed["prompt"].(string)
	if prompt == "" {
		return tool.CallResult{
			Error: fmt.Errorf("generate_image: prompt is required"),
		}, nil
	}

	resp, err := t.generator.GenerateImage(ctx, prompt)
	if err != nil {
		return tool.CallResult{
			Error: fmt.Errorf("generate_image: %w", err),
		}, nil
	}

	if len(resp.Images) == 0 {
		return tool.CallResult{
			Error: fmt.Errorf("generate_image: provider returned no images"),
		}, nil
	}

	img := resp.Images[0]
	result := map[string]any{
		"provider":  t.generator.Provider(),
		"model":     resp.Model,
		"mime_type": img.MIMEType,
	}
	if img.ImageBase64 != "" {
		result["image_base64"] = img.ImageBase64
	}
	if img.ImageURL != "" {
		result["image_url"] = img.ImageURL
	}
	if img.RevisedPrompt != "" {
		result["revised_prompt"] = img.RevisedPrompt
	}

	encoded, err := json.Marshal(result)
	if err != nil {
		return tool.CallResult{Error: err}, nil
	}

	return tool.CallResult{
		Data:        result,
		ContentType: tool.ContentTypeJSON,
		Content:     string(encoded),
	}, nil
}

// Description implements tool.Tool.
func (t *Tool) Description(_ context.Context) (string, error) {
	return ToolDescription, nil
}

// ValidateInput implements tool.Tool.
func (t *Tool) ValidateInput(_ context.Context, input map[string]any) (map[string]any, error) {
	return input, nil
}

// CheckPermissions implements tool.Tool.
func (t *Tool) CheckPermissions(_ context.Context, _ map[string]any, _ tool.ToolUseContext) types.PermissionResult {
	return types.PermissionResult{Behavior: types.PermissionBehaviorAllow}
}

// IsConcurrencySafe implements tool.Tool.
func (t *Tool) IsConcurrencySafe(_ map[string]any) bool { return true }

// IsReadOnly implements tool.Tool.
func (t *Tool) IsReadOnly(_ map[string]any) bool { return true }

// IsEnabled implements tool.Tool. Returns false when no generator is configured.
func (t *Tool) IsEnabled() bool { return t.generator != nil }

// FormatResult implements tool.Tool.
func (t *Tool) FormatResult(data any) string {
	if m, ok := data.(map[string]any); ok {
		model, _ := m["model"].(string)
		provider, _ := m["provider"].(string)
		if b64, ok := m["image_base64"].(string); ok && b64 != "" {
			return fmt.Sprintf("Image generated by %s/%s (base64, %d bytes)", provider, model, len(b64))
		}
		if url, ok := m["image_url"].(string); ok && url != "" {
			return fmt.Sprintf("Image generated by %s/%s: %s", provider, model, url)
		}
	}
	return fmt.Sprintf("%v", data)
}

// BackfillInput implements tool.Tool.
func (t *Tool) BackfillInput(_ context.Context, input map[string]any) map[string]any { return input }
